perf(core/transloco): add transloco i18n library, remove ngx.translate
gnucoop/ajf pull request #189
Opened 2021-06-25 12:35 UTC by peppedeka

2021-07-02 10:54 UTC, trik requested changes

2021-07-02 17:46 UTC, peppedeka commented on src/core/package.json
> +    "flat": "0.0.0-FLAT"
done!

2021-07-06 10:01 UTC, mrumbrella approved these changes

2021-07-06 10:09 UTC, sara-gnucoop approved these changes

2021-07-06 10:16 UTC, trik approved these changes

2021-07-06 10:16 UTC, merged