feat(core/reports): icons to text translation in pdf printing
gnucoop/ajf pull request #220
Opened 2021-08-24 17:08 UTC by robzan8

Introduces the rendering of a couple of simple icons as text.
Enables correct printing of this report https://lngb-dev.dewco.io/reports/edit/9
(the issue on taiga disappeared misteriously)

2021-08-31 06:51 UTC, sara-gnucoop approved these changes

2021-09-02 12:39 UTC, peppedeka requested changes

2021-09-02 12:39 UTC, peppedeka commented on tools/public_api_guard/core/reports.d.ts
> +export declare function createReportPdf(report: AjfReportInstance, orientation?: PageOrientation, icons: ImageMap): Promise<TCreatedPdf>;
the optional parameters are placed after mandatory parameters.

2021-09-02 12:39 UTC, peppedeka commented on tools/public_api_guard/core/reports.d.ts
> +export declare function openReportPdf(report: AjfReportInstance, orientation?: PageOrientation, icons: ImageMap): void;
the optional parameters are placed after mandatory parameters.

2021-09-06 07:11 UTC, mrumbrella approved these changes

2021-09-07 13:45 UTC, peppedeka approved these changes

2021-09-07 13:54 UTC, peppedeka approved these changes

2021-09-08 13:50 UTC, merged