feat(core/forms): add range field
gnucoop/ajf pull request #225
Opened 2021-09-02 09:40 UTC by peppedeka

add range form field for material and ionic.

2021-09-06 08:18 UTC, mrumbrella approved these changes

2021-09-06 09:03 UTC, trik requested changes

2021-09-06 09:03 UTC, trik commented on src/core/range/BUILD.bazel
> +        "@npm//@angular/cdk",
remove this, angular CDK is not used in code

2021-09-06 09:03 UTC, trik commented on src/core/range/range.ts
> +  get end(): number|undefined {
why end, start and step are not defined as inputs?

2021-09-08 07:00 UTC, peppedeka commented on src/core/range/BUILD.bazel
> +        "@npm//@angular/cdk",
done.

2021-09-08 07:00 UTC, peppedeka commented on src/core/range/range.ts
> +  get end(): number|undefined {
per dimenticanza non ho considerato il componente instanziabile da template, ora i parametri sono input

2021-09-09 09:16 UTC, sara-gnucoop approved these changes

2021-09-09 11:49 UTC, merged