Report to pdf
gnucoop/ajf pull request #52
Opened 2020-11-15 14:48 UTC by robzan8

Trik, vedi un po' se ti piace o se ci sono modifiche da fare!

2020-11-19 14:54 UTC, trik requested changes
please squash to a single commit

2020-11-19 14:54 UTC, trik commented on rollup-globals.bzl
> +    "pdfmake": "pdfmake",
this one should be
`"pdfmake/build/pdfmake": "pdfmake.build.pdfmake"`

2020-11-19 14:54 UTC, trik commented on src/core/reports/report-to-pdf/load-report-images.ts
> +import {
you can't import by module name inside the same module

2020-11-19 14:54 UTC, trik commented on src/core/reports/report-to-pdf/report-to-pdf.ts
> +import {
you can't import by module name inside the same module

2020-11-20 12:37 UTC, robzan8 commented
Updated with requested changes!

2020-11-23 14:06 UTC, robzan8 commented
Resolved conflicts with master

2020-11-27 15:25 UTC, trik approved these changes

2020-11-27 15:25 UTC, merged